### ISSUE TITLE
Investigate the possibility to change iterator tag checks for is_base_of semantics

### ISSUE THREAD

**Issue by rarutyun** [oneapi-src/oneDPL#104]
include/oneapi/dpl/pstl/utils.h file - `struct next_to_last`
test/parallel_api/algorithm/alg.modifying.operations/shift_left_right.pass.cpp file - `struct shift_right_algo`

**Comment by MikeDvorskiy** [comment]
Usage  of `is_base_of ` instead of `is_same` in shift_left_right.pass.cpp file - yes, it makes sense.
Regarding `struct next_to_last` - I don't see a sense, due to we have got no code reduction....

**Comment by rarutyun** [comment]
> Usage of `is_base_of ` instead of `is_same` in shift_left_right.pass.cpp file - yes, it makes sense. Regarding `struct next_to_last` - I don't see a sense, due to we have got no code reduction....

It's not about code reduction. It's a performance bug for C++20

**Comment by KseniiaBakina** [comment]
Implemented here https://github.com/oneapi-src/oneDPL/pull/376
