### ISSUE TITLE
SYCL kernel code has infinite loop causing error

### ISSUE THREAD

**Issue by Hongbin-Bao** [oneapi-src/oneDPL#1090]
Hi,

When I use SYCL, I have encountered a problem, when there is an infinite loop in the SYCL kernel code, it will go wrong
The following is a reproduction of the problem

The reason for the problem is that there is an infinite loop in the SYCL kernel code. Even if a certain state of the infinite loop will stop, the same error will occur. At the same time, I am not sure how large the for loop will be. This error will appear. I'm not sure why this is a problem.

The environment needs to be GPU

Create a test file:

infinite_loop.cpp

```
#include <CL/sycl.hpp>

int main() {
    cl::sycl::queue queue;

   
    std::vector<int> data(1, 42);
    cl::sycl::buffer<int, 1> buffer(data.data(), data.size());

    
    queue.submit([&](cl::sycl::handler& cgh) {
        auto acc = buffer.get_access<cl::sycl::access::mode::read_write>(cgh);

        cgh.parallel_for<class infinite_loop>(
            cl::sycl::range<1>(data.size()), 
            [=](cl::sycl::id<1> idx) {
                for(;;) { 
                    
                }
            });
    });

    queue.wait_and_throw();

    return 0;
}


```

compile and run

```
icpx -fsycl infinite_loop.cpp -o infinite_loop
```

```
./infinite_loop
```

I don't quite know why this happens, is it a design problem to save GPU resources, or a bug

**Comment by rarutyun** [comment]
Hi @Hongbin-Bao, 

Your example is pure SYCL one. There is no oneDPL API there. Could you please create the issue in [intel-llvm](https://github.com/intel/llvm) repository? It contains SYCL implementation.

Thanks.

**Comment by danhoeflinger** [comment]
Hey @Hongbin-Bao, 
I'd also recommend as you are creating the [intel-llvm](https://github.com/intel/llvm) issue to describe explicitly what your expected result is, and what specifically you are experiencing instead.
Best Regards.

**Comment by rarutyun** [comment]
By the way, if you are interested you might look [here](https://www.intel.com/content/www/us/en/docs/oneapi/installation-guide-hpc-cluster/2023-0/step-4-set-up-user-permissions-for-using-the.html).

It says: "By default, the Intel GPU driver assumes that a single concurrent task runs only for a few seconds. When running multiple processes per a single GPU, the system may hit preemption timeout, which causes the GPU program to abort. To prevent this, disable preemption checking in the kernel driver. For the compute device in use, set the preemption timeout value to zero as described below..."

But anyway, if you have more questions we suggest you to continue the dialog with [intel-llvm](https://github.com/intel/llvm) guys
