### ISSUE TITLE
question about pointer arguments for std::reduce()

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/oneDPL#1115]
Could the std::reduce() function accept pointers like std::fill() in the example ?

```
#include <oneapi/dpl/execution>
#include <oneapi/dpl/algorithm>
#include <sycl/sycl.hpp>
int main(){
  sycl::queue q;
  const int n = 1000;
  int* d_head = sycl::malloc_shared<int>(n, q);

  std::fill(oneapi::dpl::execution::make_device_policy(q), d_head, d_head + n, 42);

  sycl::free(d_head, q);
  return 0;
}
```

**Comment by mmichel11** [comment]
Hi, @jinz2014. Yes, you can pass SYCL USM pointers to reduce as input when using a device policy. This is true for passing data to all oneDPL algorithms.

For more details, the [oneDPL Developer Guide](https://www.intel.com/content/www/us/en/docs/onedpl/developer-guide/2022-2/pass-data-to-algorithms.html) states:
You can use one of the following ways to pass data to an algorithm executed with a device policy:
- oneapi:dpl::begin and oneapi::dpl::end functions

- Unified shared memory (USM) pointers and std::vector with USM allocators

- Iterators of host-side std::vector
