### ISSUE TITLE
handle sycl event

### ISSUE THREAD

**Issue by jitMatrix** [oneapi-src/oneDPL#128]
Hi, I'd like to know how I can handle the dependency when using kernels in oneDPL library.

 For example, if there comes three kernels which should be executed in order:

```kernel1 -> stable_sort -> kernel2```

how to deal with the dependency tree by using sycl event?

Really thanks:)

**Comment by reble** [comment]
https://github.com/oneapi-src/oneDPL/pull/78 introduces async algorithm for oneDPL as an experimental feature.
Return value of selected algorithm is a future that is convertible into a `sycl::event`.
Check out: 
https://github.com/oneapi-src/oneDPL/blob/reble/async-api/test/parallel_api/experimental/asynch.pass.cpp
for an example. Sort is not yet part of the test but works very similar.

**Comment by jitMatrix** [comment]
sounds good:)
