### ISSUE TITLE
oneDPL RNG engine 

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/oneDPL#1296]
Can you please add a table to show the correspondence between the oneDPL and oneMKL random number engines ?  Thanks.

minstd_rand0 | oneapi::dpl::linear_congruential_engine<std::uint32_t, 16807, 0, 2147483647>
minstd_rand | oneapi::dpl::linear_congruential_engine<std::uint32_t, 48271, 0, 2147483647>
ranlux24_base | oneapi::dpl::subtract_with_carry_engine<std::uint32_t, 24, 10, 24>
ranlux48_base | oneapi::dpl::subtract_with_carry_engine<std::uint64_t, 48, 5, 12>
ranlux24 | oneapi::dpl::discard_block_engine<ranlux24_base, 223, 23>
ranlux48 | oneapi::dpl::discard_block_engine<ranlux48_base, 389, 1

**Comment by paveldyakov** [comment]
Hi @jinz2014,
Thank you for your question. 

Currently there is no overlapping between oneDPL and oneMKL sets of supported RNG engines. 
Does it answer your question? If no, could you please provide more details about the suggested table.

**Comment by jinz2014** [comment]
I see. When there is overlapping, please contrast the engines from the two libraries in the document. Thanks.
