### ISSUE TITLE
Refactor __is_device_execution_policy to remove variadic template from top level

### ISSUE THREAD

**Issue by danhoeflinger** [oneapi-src/oneDPL#1298]
Refactor `__is_device_execution_policy` to remove unnecessary variadic template at the top level.  
Also perhaps consolidate redundant code between `__is_device_execution_policy` and  `__is_hetero_execution_policy` if possible.

2)Changes the variadic `PolicyParams` template argument to `_ExecPolicy` at higher levels, where I believe we always want exactly one Execution Policy as input.  (this could be its own PR but why not improve things while we are here)

_Originally posted by @danhoeflinger in https://github.com/oneapi-src/oneDPL/pull/1189#discussion_r1407719400_

**Comment by SergeyKopienko** [comment]
Closed: fixed in https://github.com/oneapi-src/oneDPL/pull/1300
