### ISSUE TITLE
[CI] Investigate Nuget/PIP for dependency installation

### ISSUE THREAD

**Issue by dmitriy-sobolev** [oneapi-src/oneDPL#1337]
Currently, offline installer is used on Windows. It has a drawback, which is absent with Nuget/PIP: links should be manually updated approximately once a quarter.

**Comment by danhoeflinger** [comment]
Looking a little closer at this for PIP, it seems like `dpcpp-cpp-rt` may not install the whole compiler, but just the some runtime shared libraries (Even though its description is "Intel® oneAPI DPC++/C++ Compiler").  So far, I'm not seeing a way to get the full compiler on windows via a non-conda package manager.

**Comment by danhoeflinger** [comment]
I'm closing this as I think what we have may be the best we can do for now.

**Comment by dmitriy-sobolev** [comment]
Thank you for the investigation, Dan.
