### ISSUE TITLE
Incorrect usage of `__dpl_sycl::__has_known_identity`

### ISSUE THREAD

**Issue by SergeyKopienko** [oneapi-src/oneDPL#1353]
https://github.com/oneapi-src/oneDPL/blob/de0218545ca71f8c5323858707f7266145aa046c/include/oneapi/dpl/internal/reduce_by_segment_impl.h#L608

Probably we should call ```unseq_backend::__has_known_identity``` like in other places.
Explanation: we have some definitions of ```using __has_known_identity =``` in the file https://github.com/oneapi-src/oneDPL/blob/de0218545ca71f8c5323858707f7266145aa046c/include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h#L41 and these definitions are based on SYCL version, define states and so far and so on.

**Comment by mmichel11** [comment]
I took a look at these two aliases and agree with you, we should use `unseq_backend::__has_known_identity` instead of  `__dpl_sycl::__has_known_identity`.

I will open a PR to correct it.

**Comment by SergeyKopienko** [comment]
Fine, thanks.

**Comment by mmichel11** [comment]
PR https://github.com/oneapi-src/oneDPL/pull/1362 has fixed this issue and has been merged, so I'm closing this issue.
