### ISSUE TITLE
What's mean `host policy` ?

### ISSUE THREAD

**Issue by SergeyKopienko** [oneapi-src/oneDPL#1454]
https://github.com/oneapi-src/oneDPL/blob/b66e052bec5e03d94f628f870275c5d58e76f745/documentation/library_guide/introduction.rst?plain=1#L149

Please see details at https://github.com/oneapi-src/oneDPL/pull/1239#discussion_r1530713076 :
@danhoeflinger  wrote:
- I'm not sure "host policy" is a well defined term by our documentation (its not present in our guide). In the past I've been cautioned away from using this terminology in error messages.
We do however use "device policies", "device execution policies" and "C++ Standard Execution Policies" in the guide."

**Comment by akukanov** [comment]
Resolved in the recent documentation patches
