### ISSUE TITLE
Improvements / fixes to device copyable specializations

### ISSUE THREAD

**Issue by danhoeflinger** [oneapi-src/oneDPL#1505]
@MikeDvorskiy  and I discussed some issues with device copyable.  He is working on a PR to resolve them.

The 2 issues we found which need addressing are:
1) Types with non-type template parameters (`transform_reduce`), can not match variadic typename pack 
2) Types which include template parameters which should not be checked (anything with an `ExecutionPolicy`, which includes sycl::queue for device policies, which is not device copyable)

Also, with these changes in mind, we are looking to embed the device copyable specialization in with the type definitions.  This makes things more clear, and reduces the maintenance burden of maintaining extra forward declarations in `sycl_traits.h`

**Comment by MikeDvorskiy** [comment]
There is a prototype to fix the issue: https://github.com/oneapi-src/oneDPL/pull/1513
It is we can do the best on the current moment.

**Comment by akukanov** [comment]
Addressed in #1521
