### ISSUE TITLE
Improve guidance for choosing kernel template parameters of scan based on memory requirements

### ISSUE THREAD

**Issue by adamfidel** [oneapi-src/oneDPL#1529]
From https://github.com/oneapi-src/oneDPL/pull/1320#pullrequestreview-2018418038:

> Memory footprint in SLM of joint algorithms, and how to communicate memory footprint requirements to the end user to provide them the proper guidance for selecting kernel params. I think this remains somewhat unresolved (as the sycl feature is a black box), but I think we can make a GH issue, and improve on this in the future (if we feel unsatisfied with our guidance in the docs with the current code).

**Comment by akukanov** [comment]
@adamfidel is it planned to address for 2022.7?

**Comment by adamfidel** [comment]
This issue might have been created before the documentation for the single-pass scan was finalized.

Looking at the live documentation (https://oneapi-src.github.io/oneDPL/kernel_templates/single_pass_scan.html), there is language about the SLM memory requirements based on the kernel params that users can refer to for guidance. I'm not sure if there is any thing else that needs to be done here,
