### ISSUE TITLE
Invalid macro check in `__dpl_sycl::__group_barrier` implementation

### ISSUE THREAD

**Issue by SergeyKopienko** [oneapi-src/oneDPL#1615]
https://github.com/oneapi-src/oneDPL/blob/f53c8e7a24a8378b2566295c66bfe05771cd9384/include/oneapi/dpl/pstl/hetero/dpcpp/sycl_defs.h#L170

Please see details in https://github.com/intel/llvm/issues/12531
Please see details in https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_group_broadcast

**Comment by akukanov** [comment]
Duplicates #1679 where some discussion is already going.
