### ISSUE TITLE
Simplify tag dispatching in c++20 ranges

### ISSUE THREAD

**Issue by MikeDvorskiy** [oneapi-src/oneDPL#1807]
As we discussed, everything can be simplified to two overload, without `_impl` one. Line 59 would have `__serial_tag<std::false_type>` and another one would have generic `_Tag` with the same static assert as you have in `_impl`. Thus, you could avoid compile-time branches duplication.

_Originally posted by @rarutyun in https://github.com/oneapi-src/oneDPL/pull/1457#discussion_r1737645956_

**Comment by dmitriy-sobolev** [comment]
This issue can be closed, because the proposed approach was implemented in #1457.
