### ISSUE TITLE
std or oneapi::dpl namespace

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/oneDPL#1892]
Sorry, I don't know if people asked the question before. Could you please explain or clarify which namespace a user should use for a function in a SYCL program ? 

For example, std::reduce or oneapi::dpl::reduce.

Is one namespace (oneapi::dpl::reduce) better than two namespaces ?

**Comment by akukanov** [comment]
The specification of oneDPL says that the namespace for all its functionality is `oneapi::dpl`, and a shorter alias `dpl` can be used as well; see https://oneapi-spec.uxlfoundation.org/specifications/oneapi/latest/elements/onedpl/source/common. There is similar note in the library guide: https://oneapi-src.github.io/oneDPL/introduction.html. This is the preferred way of using the oneDPL functions.

**Comment by jinz2014** [comment]
I hope the oneDPL documentation will remove "std::".
