### ISSUE TITLE
Building Intel Media-Transport-Library with oneDPL

### ISSUE THREAD

**Issue by chenzuozhou** [oneapi-src/oneDPL#1926]
I want to build media-transport-library with oneDPL, and I'm trying to set icx compiler, the command is "CC=icx CXX=icpx meson .....", when run this command, it reports error, here is the error infos: 
..........
meson.build:1:0: ERROR: Tried to use unknown language "icx"
........

**Comment by dmitriy-sobolev** [comment]
It does not look like a oneDPL-specific question, but a let me help.

I guess this is what you are looking for: 
Windows: `-DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icx -GNinja`
Linux: `-DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icpx`

It is described here: https://www.intel.com/content/www/us/en/docs/dpcpp-cpp-compiler/developer-guide-reference/2025-0/use-cmake-with-the-compiler.html

**Comment by dmitriy-sobolev** [comment]
I am closing that issue, assuming the question was answered. If it was not, feel free to reopen it.
