### ISSUE TITLE
demo examples 

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/oneDPL#34]
May you please add code examples for the extension APIs (e.g. the segmented scan and reduce) ?

Thank you

**Comment by BenFrantzDale** [comment]
Yeah. The examples link is dead :-/

**Comment by capatober** [comment]
> Yeah. The examples link is dead :-/

Sorry. The correct link is https://github.com/oneapi-src/oneAPI-samples/tree/master/Libraries/oneDPL

**Comment by timmiesmith** [comment]
Tests for the segmented scan and reduce APIs are available in [numeric.ops](https://github.com/oneapi-src/oneDPL/tree/main/test/parallel_api/numeric/numeric.ops).  If there's a specific use case you'd like to see demonstrated that isn't covered in the test please let us know.
