### ISSUE TITLE
Can't run demo code with UHD630 cause ERROR InvalidBuiltinSetName: Expects OpenCL12, OpenCL20. 

### ISSUE THREAD

**Issue by CKboss** [oneapi-src/oneDPL#400]
Can't run demo code with UHD630
Throw error InvalidBuiltinSetName: Expects OpenCL12, OpenCL20.  Actual is OpenCL.DebugInfo.100

```
Intel(R) FPGA Emulation Platform for OpenCL(TM)
Device: Intel(R) FPGA Emulation Device
Intel(R) OpenCL
Device: Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz
Intel(R) OpenCL HD Graphics
Device: Intel(R) UHD Graphics 630
SYCL host platform
Device: SYCL host device
Running on device: Intel(R) UHD Graphics 630
driver_version: 27.20.100.8681
max_computer_units: 23
local_computer_units: 65536
Vector size: 10000
InvalidBuiltinSetName: Expects OpenCL12, OpenCL20. Actual is OpenCL.DebugInfo.100 [Src: D:\qb\workspace\21461\source\gfx
-driver\Source\IGC\AdaptorOCL\SPIRV\libSPIRV\SPIRVModule.cpp:565 SPIRVBuiltinSetNameMap::rfind(BuiltinSetName, &BuiltinS
et) ]

internal compiler error, abnormal program termination
```

**Comment by dsobolev-dev** [comment]
Hi, @CKboss.  It may be some environment configuration issue. Could you try the latest driver: https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html and check if this solves the problem?

**Comment by CKboss** [comment]
Solved when update the driver to 30.0.100.9955

**Comment by AJIOB** [comment]
Have the same error in Debian 9-based Linux. 

What do I need to rebuild to fix that issue?
Where I can find sources for that?

**Comment by dmitriy-sobolev** [comment]
@AJIOB, unfortunately,  Debian 9 is not supported for GPU: https://www.intel.com/content/www/us/en/developer/articles/system-requirements/intel-oneapi-base-toolkit-system-requirements.html (search "Linux distribution for GPU Accelerators").

There is an instruction to install the latest GPU driver: https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-focal.html. 
As the latest driver does not support Ubuntu 18.04, it may not suit you. I suggest trying https://github.com/intel/compute-runtime/releases/tag/21.33.20678, which is the latest driver supporting Ubuntu 18.04, by following installation procedure chapter. This GPU driver version should work with Debian 10 too and less probably with Debian 9.
