### ISSUE TITLE
New known limitation: the usage of std::vector

### ISSUE THREAD

**Issue by ValentinaKats** [oneapi-src/oneDPL#519]
To add this limitation to documentation. 

The root cause of this compile error is that std::vector<bool> is not a vector of some bools, it is a vector of bytes. Each item of source vector is only one bit in memory of this bytes vector: https://en.cppreference.com/w/cpp/container/vector_bool
So we can't use std::vector<bool> with our algorithms because of this limitation: SYCL library now sometimes tried to get address of vector item, but for std::vector<bool> this operation is not applicable.
@ValentinaKats please add this limitation to our doc.

_Originally posted by @SergeyKopienko in https://github.com/oneapi-src/oneDPL/pull/517#discussion_r806479027_

**Comment by dmitriy-sobolev** [comment]
This is not a limitation, but rather an issue on the side of oneAPI Data Parallel C++ compiler. It has been fixed in https://github.com/intel/llvm/pull/5609. 
The issue prevented construction of `sycl::buffer` using `std::vector<bool>`.
