### ISSUE TITLE
SYCL backend minor refactoring: forwarding policy and usage of sycl::queue

### ISSUE THREAD

**Issue by MikeDvorskiy** [oneapi-src/oneDPL#522]
It's still dangerous to forward policy keeping in mind that we use it later. But as we discussed there lots of such places. We need to either do global refactoring for that or reconsider the approach. Please create the separate issue with that regard.

_Originally posted by @rarutyun in https://github.com/oneapi-src/oneDPL/pull/501#discussion_r809909310_

**Comment by SergeyKopienko** [comment]
These issues already has been fixed at https://github.com/oneapi-src/oneDPL/commit/a1b674023e602f39f0d30a5f44e56cb0af3eecd7
