### ISSUE TITLE
help with getting transform_reduce to work for device array

### ISSUE THREAD

**Issue by mgrabban** [oneapi-src/oneDPL#529]
Hello,
Can you please help with finding the issue with the following code?
More specifically, I am trying to apply std::transform_reduce on a device pointer (allocated using malloc_device and populated with memcpy). I want to first apply abs, and then take the max. I understand std::transform, std::reduce, std::transform_reduce each needs an iterator and usm allocated array/buffer should work (not 100% sure). It does work for std::transform (without any explicit conversion of the device pointer to an iterator but It fails for both std::reduce and std::transform_reduce. 

```
#include <oneapi/dpl/execution>
#include <oneapi/dpl/algorithm>
#include <CL/sycl.hpp>

#include <vector>
#include <iostream>

struct FunctionalAbs {
    float operator()(const float& x) const {
        return sycl::fabs((float)x);
    }
};

constexpr int N = 16;

int main()
{
    // create queue and policy
    sycl::queue myQueue = sycl::queue();
    auto policy = oneapi::dpl::execution::make_device_policy(myQueue);

    // fill up host vecotr
    std::vector<float> values_h;
    for (int i = 0; i < N; ++i) {
        values_h.push_back(-(float)N/2 + i);
    }

    // allocate and fill up device pointer
    auto values_d = sycl::malloc_device<float>(N, myQueue);
    myQueue.memcpy(values_d, &values_h[0], N * sizeof(float)).wait();

    /* THIS WORKS */
    // transform and reduce host vector: takes abs followed by max
    float max_h = std::transform_reduce(    // works
        values_h.begin(),
        values_h.end(),
        0.0f,
        oneapi::dpl::maximum<float>(),
        FunctionalAbs());

    /* THIS IS NOT WORKING */
    float max_d = std::transform_reduce(    // does not work
        policy,
        values_d,       // how to get an iterator here
        values_d + N,   // how to get an iterator here
        0.0f,
        oneapi::dpl::maximum<float>(),
        FunctionalAbs());
    
    /* THIS WORKS */
    std::transform(                         // works
        policy,
        values_d,       // does not require iterator here
        values_d + N,   // does not require iterator here
        values_d,
        FunctionalAbs());

    std::cout << "max: " << max_h << std::endl;

    return 0;
}
```
I get this error when trying to compile using dpcpp test_transform_reduce.cpp

`test_transform_reduce.cpp:42:19: error: no matching function for call to 'transform_reduce'
    float max_d = std::transform_reduce(    // does not work
                  ^~~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/numeric:338:5: note: candidate template ignored: deduced conflicting types for parameter '_InputIterator1' ('oneapi::dpl::execution::device_policy<>' vs. 'float *')
    transform_reduce(_InputIterator1 __first1, _InputIterator1 __last1,
    ^
/usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/pstl/glue_numeric_impl.h:81:1: note: candidate template ignored: requirement '__pstl::execution::is_execution_policy<oneapi::dpl::execution::device_policy<oneapi::dpl::execution::DefaultKernelName>>::value' was not satisfied [with _ExecutionPolicy = oneapi::dpl::execution::device_policy<> &, _ForwardIterator = float *, _Tp = float, _BinaryOperation = oneapi::dpl::maximum<float>, _UnaryOperation = FunctionalAbs]
transform_reduce(_ExecutionPolicy&& __exec, _ForwardIterator __first, _ForwardIterator __last, _Tp __init,
^
/usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/numeric:405:5: note: candidate function template not viable: requires 5 arguments, but 6 were provided
    transform_reduce(_InputIterator __first, _InputIterator __last, _Tp __init,
    ^
/usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/pstl/glue_numeric_impl.h:54:1: note: candidate function template not viable: requires 5 arguments, but 6 were provided
transform_reduce(_ExecutionPolicy&& __exec, _ForwardIterator1 __first1, _ForwardIterator1 __last1,
^
/usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/pstl/glue_numeric_impl.h:69:1: note: candidate function template not viable: requires 7 arguments, but 6 were provided
transform_reduce(_ExecutionPolicy&& __exec, _ForwardIterator1 __first1, _ForwardIterator1 __last1,
^
/usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/numeric:380:5: note: candidate function template not viable: requires 4 arguments, but 6 were provided
    transform_reduce(_InputIterator1 __first1, _InputIterator1 __last1,
    ^
1 error generated.`

Thanks,
Golam

**Comment by lilohuang** [comment]
Somehow using oneapi::dpl::transform_reduce() instead of std::transform_reduce() can get rid of the compilation error.

**Comment by rarutyun** [comment]
As I see the reason, why it works for `std::transform`, is you use `#include <oneapi/dpl/algorithm>` where both `std::transform `and `oneapi::dpl::transform` are defined for the `policy` you are trying to pass to algorithm.
Both `oneapi::dpl::tranform_reduce` and `std::transform_reduce` are in defined in <oneapi/dpl/numeric> header (symmetrically with `<numeric>` header for `std::transform_reduce` from C++ standard library).

So, I am almost sure that you should be able to use both `std::transform` and `std::transform_reduce` with the `policy` you are trying to use just by adding `#include <oneapi/dpl/numeric>` in the code snippet.

Please let me know if it helps with the problem.

**Comment by rarutyun** [comment]
@lilohuang 

> Somehow using oneapi::dpl::transform_reduce() instead of std::transform_reduce() can get rid of the compilation error.

As mentioned in my previous comment both `oneapi::dpl::tranform_reduce` and `std::transform_reduce` are in defined in `<oneapi/dpl/numeric>` header. `oneapi::dpl::transform_reduce` might be occasionally available from other headers (as it might happen for any other API from any C++ library) but that is not how it is supposed to be used. You still should include `<oneapi/dpl/numeric>` header.

**Comment by mgrabban** [comment]
Thank you, [Lilo Huang](https://github.com/lilohuang) and [Ruslan Arutyunyan](https://github.com/rarutyun)!
I can confirm both suggestions work for me. This is the first time I was using oneDPL for converting a CUDA w/ thrust workload to DPC++. Nice to know prompt help is available :-)

**Comment by mgrabban** [comment]
Hi,
I closed this issue as it is resolved but I have an unrelated question so I am reopening it. Sorry.
I have used dpct tool to convert a CUDA workload to dpc++. The cuda code uses lots of thrust features and in converted code, dpct creates its own header that defines these features. But I have restriction on using dpct headers so the thrust features have to be rewritten.
Is oneDPL the closest Intel library that is parallel to NVIDIA thrust? If you are aware of any such other Intel libraries, can you please point me to it. Thanks!

**Comment by rarutyun** [comment]
I believe, yes, oneDPL is the closest library to Thrust. It might depend on the functionality you need, though, but if talking about Parallel Algorithms I don't know closer library than oneDPL.

If you have some specific questions about DPCT I suppose @timmiesmith could help. But I would suggest to create separate issue for that.

If you have specific questions how some code from Thrust could be expressed with oneDPL (if no direct or no obvious mapping exist) you have two options:
- feel free to ask with specific examples what Thrust feature you need
- Look at the DPCT resulting header:)

Also you might go though our github to find similar issues that you have (if you like).

Anyway, I believe separate issue would be the right way.

**Comment by mgrabban** [comment]
Thanks for your suggestions! I really appreciate it. Closing the issue now.
