### ISSUE TITLE
[oneapi][doc][spec] To add the details about alias "namespace dpl = oneapi::dpl" to the spec or(and) the doc

### ISSUE THREAD

**Issue by MikeDvorskiy** [oneapi-src/oneDPL#564]
(2) - @ValentinaKats Could you please add details about alias "namespace dpl = oneapi::dpl" to the OneAPI spec or(and) oneAPI documentation?

_Originally posted by @SergeyKopienko in https://github.com/oneapi-src/oneDPL/pull/558#discussion_r832914117_

**Comment by akukanov** [comment]
This is what the specification says (https://oneapi-spec.uxlfoundation.org/specifications/oneapi/latest/elements/onedpl/source/common):

> oneDPL uses `namespace oneapi::dpl` and a shorter variant `namespace dpl` **for all functionality** including parallel algorithms, oneDPL execution policies, etc.

If you think it needs to be clarified, please suggest how (a wording or at least a direction).

The documentation does not say anything about the `namespace dpl`. This is what it has as a general description (https://oneapi-src.github.io/oneDPL/introduction.html):

> oneDPL introduces the namespace oneapi::dpl for most its classes and functions.

For many APIs their namespace (usually `namespace oneapi::dpl`) is explicitly mentioned. A few examples use `dpl::` together with `using namespace oneapi;` directive (which I want to get rid of, honestly).

Same request: if you have an idea what to improve in that regard in the library guide, please provide feedback.

@SergeyKopienko @danhoeflinger @timmiesmith @rarutyun

**Comment by SergeyKopienko** [comment]
My assumption - we may have in documentation some list of public [Namespase aliases](https://en.cppreference.com/w/cpp/language/namespace_alias) :
- in this case :  dpl <-> oneapi::dpl

I mean users should have some list of that.

**Comment by akukanov** [comment]
https://github.com/oneapi-src/oneDPL/pull/1825 adds a note to `introduction.rst`. Good enough?

**Comment by SergeyKopienko** [comment]
> #1825 adds a note to `introduction.rst`. Good enough?
Yes, I think so. Thanks.
