### ISSUE TITLE
std::inner_product question

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/oneDPL#570]
Is std::inner_product supported by oneDPL ?

https://github.com/NVIDIA/thrust/blob/main/examples/word_count.cu

Thanks

**Comment by MikeDvorskiy** [comment]
Hello @zjin-lcf ,

Actually, `std::inner_product` has not an overload with an execution policy. So, oneDPL  has not such algorithm with parallel and heterogeneous execution.
To get `inner_product` semantic with a parallel execution on device(or host) you should use `oneapi::dpl::transform_reduce`.

Additional comment: you can execution serial `oneapi::dpl::inner_product` (as using ::std::inner_product;) within kernel if you need serial execution by a work item.
