### ISSUE TITLE
onedpl support for NVIDIA and AMD hardware

### ISSUE THREAD

**Issue by mgrabban** [oneapi-src/oneDPL#575]
Hello,

Does oneDPL support NVIDIA as well as AMD backend?
If yes, can you please provide  with some instructions on how to use it with the open source DPC++ (syclos)?
If no, is there any plan to support those hardwires?

Thanks,
Golam

**Comment by timmiesmith** [comment]
Codeplay has contributed support for CUDA to the oneAPI project, delivering support for Nvidia GPUs to the open-source DPC++ compiler. You can find information about Codeplay's efforts at
[oneAPI for CUDA](https://codeplay.com/solutions/oneapi/for-cuda/)

Support for AMD hardware is also provided through the DPC++ compiler. The instructions on building the compiler with CUDA support and HIP support are at the links below.

[CUDA](https://intel.github.io/llvm-docs/GetStartedGuide.html#build-dpc-toolchain-with-support-for-nvidia-cuda)
[AMD](https://intel.github.io/llvm-docs/GetStartedGuide.html#build-dpc-toolchain-with-support-for-hip-amd)

Finally, [open-source DPC++ repo](https://github.com/intel/llvm#oneapi-data-parallel-c-compiler) is where you can find the compiler source.

**Comment by mgrabban** [comment]
Thanks for your response!
I am aware of Codeplay contributed open-source DPC++. In fact, I run some of my workloads on NVIDIA/AMD hardware using it. 
But my specific question is does this open-source DPC++ has oneDPL support included (I could not find any reference to NVIDIA/AMD in this repo)? If yes, would you know how to use? When I try to build my code using open-source DPC++, it gives error saying it can't find oneDPL. BTW I use some reduce and transform_reduce from oneDPL.

**Comment by timmiesmith** [comment]
oneDPL is expected to run on the CUDA and HIP backends provided by the open-source DPC++ compiler, so there's no platform specific code in this repo. Building your code with the open-source DPC++ would require cloning this repo and including the oneDPL/include directory in your include path.  Please upload a compile log if it's not working as expected.

**Comment by mgrabban** [comment]
Thanks for the information.
I am able to compile and run on both NVIDIA and AMD GPUs. Note in addition to including oneDPL/include, I had to (clone oneTBB and) include oneTBB/include.

**Comment by zjin-lcf** [comment]
> Thanks for the information. I am able to compile and run on both NVIDIA and AMD GPUs. Note in addition to including oneDPL/include, I had to (clone oneTBB and) include oneTBB/include.

I hope the oneDPL docs can include your comments.
