### ISSUE TITLE
reference to 'match_results' is ambiguous

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/oneDPL#576]
In DevCloud, I got the following message when compiling a source file containing an oneDPL function and a MKL USM function. Thank you for your suggestion.

The compiler is icpx, located at /glob/development-tools/versions/oneapi/2022.1.2/oneapi/compiler/2022.0.2/linux/bin/icpx
 oneDPL header files are included before the standard C++ header files

```
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/regex:62:
/usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/regex.h:54:9: error: reference to 'match_results' is ambiguous
                      match_results<_BiIter, _Alloc>&      __m,
                      ^
/glob/development-tools/versions/oneapi/2022.1.2/oneapi/dpl/2021.6.0/linux/include/oneapi/dpl/pstl/ranges/nanorange.hpp:3241:7: note: candidate found by name lookup is 'std::match_results'
class match_results;
      ^
/usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/regex.h:39:11: note: candidate found by name lookup is 'std::__cxx11::match_results'
    class match_results;
```

**Comment by timmiesmith** [comment]
Would you please provide your source file so we can investigate?  Thank you.

**Comment by zjin-lcf** [comment]
They are located at
https://github.com/zjin-lcf/HeCBench/tree/master/si-sycl

The compile instructions are listed in the README.md

Thanks

**Comment by timmiesmith** [comment]
Hi, @zjin-lcf. I'm investigating this issue. As a workaround, would you please try adding `-DNANORANGE_NO_STD_FORWARD_DECLARATIONS` to your compilation options?  That resolves the compile error for me, but others remain that may be due to other issues in my environment.
