### ISSUE TITLE
could std::transform_reduce accept USM or device pointers ?

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/oneDPL#577]
The example shows that std::fill() can accept a USM pointer.
```
#include <oneapi/dpl/execution>
#include <oneapi/dpl/algorithm>
#include <CL/sycl.hpp>
int main(){
  sycl::queue q;
  const int n = 1000;
  int* d_head = sycl::malloc_shared<int>(n, q);

  std::fill(oneapi::dpl::execution::make_device_policy(q), d_head, d_head + n, 42);

  sycl::free(d_head, q);
  return 0;
}
```

However, my test shows that std::transform_reduce does not accept it. Is that right ?

Thanks

**Comment by timmiesmith** [comment]
That's not expected. `std::transform_reduce` should accept USM pointers as your example with `std::fill` does. Can you post the invocation of `std::transform_reduce` from your code so we can be sure we're investigating the correct interface?  Thank you.

**Comment by timmiesmith** [comment]
The example below shows that `std::transform_reduce` is able to accept USM pointers as well. Please let me know if you're having issues with another of the `transform_reduce` interfaces.

`#include <oneapi/dpl/execution>
#include <oneapi/dpl/algorithm>
#include <oneapi/dpl/numeric>
#include <CL/sycl.hpp>
int main(){
  sycl::queue q;
  const int n = 1000;
  int* d_head = sycl::malloc_shared<int>(n, q);
  int* c_head = sycl::malloc_shared<int>(n, q);

  std::fill(oneapi::dpl::execution::make_device_policy(q), d_head, d_head + n, 42);
  std::fill(oneapi::dpl::execution::make_device_policy(q), c_head, c_head + n, 2);

  std::transform_reduce(oneapi::dpl::execution::make_device_policy(q), d_head, d_head + n, c_head, 0);
  sycl::free(d_head, q);
  return 0;
}
`

**Comment by zjin-lcf** [comment]
Thank you for the example. 

Please see the example: https://github.com/zjin-lcf/HeCBench/tree/master/kurtosis-sycl

I type 'make CC=dpcpp' in DevCloud

The cuda version is https://github.com/zjin-lcf/HeCBench/tree/master/kurtosis-cuda

Thanks.

**Comment by timmiesmith** [comment]
The `transform_reduce` algorithm is provided through the header `oneapi/dpl/numeric`.  If you'll include this at the top of main.cpp with the other oneDPL headers the code will compile without error, though there are two warnings on my system.
