### ISSUE TITLE
Executing algorithms on subdevices broken with Intel LLVM trunk

### ISSUE THREAD

**Issue by BenBrock** [oneapi-src/oneDPL#657]
I'm not sure whether this is a bug in oneDPL or in DPC++, but launching oneDPL algorithms on SYCL subdevices (e.g. one tile of a PVC) seems to be broken in most recent LLVM trunk.

I encountered this bug with both 2021.7.0 and the `main` branch of oneDPL.  My DPC++ is an open-source build from commit `77b1e9dfef554d8e686a373553d3898d6833f5d8` built with all default options and NVIDIA support enabled.

The following minimal example demonstrates the bug.  I expect `reduce` to run successfully on a single device as well as subdevice, but it crashes when oneDPL `reduce` is called with an execution policy on a subdevice with the following output:

```
(base) bbrock@sdp135223:~/src/oneDPL_subdevice$ ./very_minimized 
Reducing on device...
Allocating memory on subdevice...
Result is 0
Reducing on subdevice...
Allocating memory on subdevice...
terminate called after throwing an instance of 'sycl::_V1::exception'
  what():  Not all devices are associated with the context or vector of devices is empty
Aborted (core dumped)
```

There is only a single device given to oneDPL's execution policy, so the error doesn't make a ton of sense to me.

```cpp
#include <CL/sycl.hpp>
#include <oneapi/dpl/execution>
#include <oneapi/dpl/async>
#include <oneapi/dpl/numeric>
#include <cstdio>

void test_device(sycl::context context, sycl::device device) {
  size_t size = 100;
  int* a;

  printf("Allocating memory on subdevice...\n");
  a = sycl::malloc_device<int>(size, device, context);
  oneapi::dpl::execution::device_policy policy(device);

  int result = oneapi::dpl::reduce(policy, a, a+100, float(0), std::plus());

  printf("Result is %d\n", result);
}

int main(int argc, char** argv) {
  sycl::gpu_selector g;
  sycl::device device = sycl::device(g);
  auto subdevices = device.create_sub_devices<sycl::info::partition_property::partition_by_affinity_domain>(sycl::info::partition_affinity_domain::numa);

  printf("Reducing on device...\n");
  sycl::context device_context(device);
  test_device(device_context, device);

  printf("Reducing on subdevice...\n");
  sycl::context subdevice_context(subdevices);
  test_device(subdevice_context, subdevices[0]);

  return 0;
}
```

**Comment by BenBrock** [comment]
Just confirmed that this issue persists with the most recent DPC++ and oneDPL (`c49eeda87e2dedddcdb3a82de98868c95f7d5009` and `b7cfc8d5f0569dc61a23e2d0fa3b70116fa2d4ed`).

This is a major performance issue on PVC, as it prevents the user from using explicit scaling whenever oneDPL is used.

**Comment by aelovikov-intel** [comment]
With current https://github.com/intel/llvm: https://gist.github.com/aelovikov-intel/399b2807b5a32f9018922e98083d936c

One can try `SYCL_ENABLE_DEFAULT_CONTEXTS=0` as a temporary workaround. Long-term fix is dependent on the resolution of https://github.com/KhronosGroup/SYCL-Docs/issues/313.

**Comment by rarutyun** [comment]
> Just confirmed that this issue persists with the most recent DPC++ and oneDPL (`c49eeda87e2dedddcdb3a82de98868c95f7d5009` and `b7cfc8d5f0569dc61a23e2d0fa3b70116fa2d4ed`).
> 
> This is a major performance issue on PVC, as it prevents the user from using explicit scaling whenever oneDPL is used.

Yep, what @aelovikov-intel suggested seems fine and can be a good way to overcome that issue if you need to change the behavior for the whole binary you are compiling. If, however, you do need to change the behavior case by case (or API call by API call) you may try another way of interacting with oneDPL:

```cpp
#include <CL/sycl.hpp>
#include <oneapi/dpl/execution>
#include <oneapi/dpl/async>
#include <oneapi/dpl/numeric>
#include <cstdio>

void test_device(sycl::context context, sycl::device device) {
  size_t size = 100;
  int* a;

  printf("Allocating memory on subdevice...\n");
  sycl::queue q(context, device);
  a = sycl::malloc_device<int>(size, q);
  oneapi::dpl::execution::device_policy policy(q);

  int result = oneapi::dpl::reduce(policy, a, a+100, float(0), std::plus());

  printf("Result is %d\n", result);

  sycl::free(a, q);
}

int main(int argc, char** argv) {
  sycl::gpu_selector g;
  sycl::device device = sycl::device(g);
  auto subdevices = device.create_sub_devices<sycl::info::partition_property::partition_by_affinity_domain>(sycl::info::partition_affinity_domain::numa);

  printf("Reducing on device...\n");
  sycl::context device_context(device);
  test_device(device_context, device);

  printf("Reducing on subdevice...\n");
  sycl::context subdevice_context(subdevices);
  test_device(subdevice_context, subdevices[0]);

  return 0;
}
```

So, what I've changed above is I've constructed ``sycl::queue`` and continued working with that in both SYCL and oneDPL APIs. It would allow you to control what you want to do for each particular call rather than for the whole binary.

I believe both suggestions should work. Please choose whatever you prefer. I just wanted to make sure you have alternatives to play with.

**Comment by aelovikov-intel** [comment]
> Just for my own curiosity, am I to understand that under the current SYCL standard, there's really no guarantee of a reasonable global context being selected when creating a queue on a device

IIUC, SYCL itself states that a new context containing just that device is created. Having platform default device is an extension that is enabled in our implementation on Linux by default.

That said, the issue here is somewhat orthogonal to that (how kernel bundles interact with subdevices), although it only presents itself in one case and not in the other.

**Comment by BenBrock** [comment]
Yes, happy to have you close the issue.

**Comment by rarutyun** [comment]
The solution that works in current circumstances was suggested. When SYCL specification is extended to support the scenario described in that issue the use-case should work out of the box without additional steps.
