### ISSUE TITLE
Fix `async` and `execution` include order issue?

### ISSUE THREAD

**Issue by BenBrock** [oneapi-src/oneDPL#658]
Including `async` before `execution` currently results in a failed compilation with errors complaining that the template `oneapi::dpl::__internal::__is_device_execution_policy` is not defined.  Would it be possible to fix this, e.g. by having `async` include `execution`, or is that not possible?

```cpp
#include <oneapi/dpl/async>

int main() { return 0; }
```

**Comment by rarutyun** [comment]
Fixed with PR #677
