### ISSUE TITLE
50707 compiler version check should be fixed

### ISSUE THREAD

**Issue by rarutyun** [oneapi-src/oneDPL#695]
50707 is the version of the compiler that has never existed. They didn't change patch version at all upon the time. The problem is if we do the right check that is __LIBSYCL_VERSION >= 50700 the code would be broken. It's unclear what can be achieved with just changing the patch version. The compiler is supposed the new API version in 60000 so the version should be corrected.

See #630 for the change details and the comment with the same text:)

**Comment by SergeyKopienko** [comment]
Fixed in https://github.com/oneapi-src/oneDPL/pull/707
