### ISSUE TITLE
The workaround with swapping the overloads to overcome the compiler bug is not properly commented

### ISSUE THREAD

**Issue by rarutyun** [oneapi-src/oneDPL#720]
There are many places in `glue_algorithm_defs`, please see `is_heap` as the reference.

**Comment by SergeyKopienko** [comment]
@rarutyun could you please close this issue?
Let's continue in the created PR https://github.com/oneapi-src/oneDPL/pull/791

**Comment by SergeyKopienko** [comment]
PR PR https://github.com/oneapi-src/oneDPL/pull/791 were merged into main branch.
