### ISSUE TITLE
execution header has something weird wrt namespaces

### ISSUE THREAD

**Issue by Ri0n** [oneapi-src/oneDPL#759]
```
namespace oneapi
{
namespace dpl
{
namespace execution
{
using namespace oneapi::dpl::execution;
} // end namespace execution
} // end namespace dpl
} // end namespace oneapi
```

This part doesn't build with Visual Studio when warnings are treated as errors because namespace uses itself.

see
https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4515?view=msvc-170

Example of error:
```
C:\Users\Jenkins\.conan\data\pstl\2021.7.1\mcdcore\stable\package\690bf0d4b737d389285e923a75630da538e8affb\include\oneapi/dpl/execution(76): error C2220: the following warning/  is treated as an error
C:\Users\Jenkins\.conan\data\pstl\2021.7.1\mcdcore\stable\package\690bf0d4b737d389285e923a75630da538e8affb\include\oneapi/dpl/execution(76): warning C4515: 'execution': namespace uses itself
```

**Comment by SergeyKopienko** [comment]
@Ri0n, thank you for this info. This issue will be fixed asap.

**Comment by SergeyKopienko** [comment]
@Ri0n this issue were fixed in https://github.com/oneapi-src/oneDPL/pull/790 and merged into main branch.
Could you please check this error on fresh version of oneDPL code and confirm that now this error fixed?
Thanks.

**Comment by SergeyKopienko** [comment]
This issue were fixed in https://github.com/oneapi-src/oneDPL/pull/790.
@Ri0n, thank you for info.
