### ISSUE TITLE
Build error: functional-style cast, buffer_wrapper.pass

### ISSUE THREAD

**Issue by abagusetty** [oneapi-src/oneDPL#788]
```[bash]
...../oneDPL/test/general/buffer_wrapper.pass.cpp:37:26: error: no matching conversion for functional-style cast from 'sycl::buffer<unsigned int, dim, aligned_allocator<unsigned int>>' to 'sycl::host_accessor<const unsigned int, 1, sycl::access_mode::read>'
        T* actual_data = sycl::host_accessor<T, 1, sycl::access_mode::read>(buf).get_pointer();
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by SergeyKopienko** [comment]
@abagusetty, could you please specify on which compiler you received this compile error?

**Comment by abagusetty** [comment]
@SergeyKopienko Thanks for looking into it. I have just tried with this commit [hash](fdf63c45d86062665193c9935155d6688e73ba7c).

**Comment by abagusetty** [comment]
@SergeyKopienko Thanks for such a prompt fix #793

Compiler was built with this hash from source: https://github.com/intel/llvm/commit/1ed2378b6072a0f70c55f4105339b527c7015a75
With C++ 17.

**Comment by SergeyKopienko** [comment]
@abagusetty, thank you for this update.
May you check our fix from https://github.com/oneapi-src/oneDPL/pull/793 and send me info that this issue is resolved?

**Comment by abagusetty** [comment]
Just checked. This issue is resolved. Thanks again!

**Comment by SergeyKopienko** [comment]
Thank you, @abagusetty !
