### ISSUE TITLE
Test hangs when compiled with sub-group size=16

### ISSUE THREAD

**Issue by abagusetty** [oneapi-src/oneDPL#839]
I building the tests by setting the sub-group size to 16 `-DCMAKE_CXX_FLAGS="-fsycl-default-sub-group-size=16"` to cmake build options for PVC. Would appreciate if some one can confirm. Are there any limitations imposed by sub-group sizes.

One such test is: `dpl_namespace.pass` hangs for some reason but it doesn't hang with `-fsycl-default-sub-group-size=32`. Also all the 321 tests pass when the sub-group size is set to 32. I have noticed that several others like: `sycl_iterator_for, find, scan, sort` all these hangs as well. These are just handful of tests, I ran manually (i.e., not using ctest).

Using just 1-tile: `ZE_AFFINITY_MASK=0.0` 
Compiler: 
```bash
clang version 17.0.0 (https://github.com/intel/llvm.git fea99cc9ad676afeb7fa3404f7db598e42804468)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /lus/gila/projects/Aurora_deployment/intel_anl_shared_CNDA/llvm/build_l0/bin
Found candidate GCC installation: /opt/cray/pe/gcc/11.2.0/snos/lib/gcc/x86_64-suse-linux/11.2.0
Selected GCC installation: /opt/cray/pe/gcc/11.2.0/snos/lib/gcc/x86_64-suse-linux/11.2.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
```
More Info:
Upon using `SYCL_PI_TRACE=-1 dpl_namespace.pass` the following seems to hang with the synchronization.
```bash
.....
PI ---> Arg.Value->getZeHandlePtr(ZeHandlePtr, Arg.AccessMode, Queue->Device)
PI ---> getZeHandle(ZeHandle, AccessMode, Device)
PI ---> Arg.Value->getZeHandlePtr(ZeHandlePtr, Arg.AccessMode, Queue->Device)
PI ---> getZeHandle(ZeHandle, AccessMode, Device)
PI ---> Arg.Value->getZeHandlePtr(ZeHandlePtr, Arg.AccessMode, Queue->Device)
PI ---> getZeHandle(ZeHandle, AccessMode, Device)
PI ---> Queue->insertStartBarrierIfDiscardEventsMode(CommandList)
PI ---> EventCreate(Queue->Context, Queue, ForceHostVisible, Event)
PI ---> piEventRetain(*Event)
PI ---> piKernelRetain(Kernel)
) ---> 	pi_result : PI_SUCCESS
	[out]pi_event * : 0x2a8bf90[ 0x2ab22e0 ... ]
	[out]pi_event * : 0x2a8d2f8[ 0x2a8e270 ... ]

---> piKernelRelease(
	<unknown> : 0x1d25ac0
) ---> 	pi_result : PI_SUCCESS

---> piKernelRelease(
	<unknown> : 0x1d1d040
) ---> 	pi_result : PI_SUCCESS

---> piEventsWait(
	<unknown> : 1
	pi_event * : 0x2a8d2f8[ 0x2a8e270 ... ]
```

**Comment by mmichel11** [comment]
Hello, thank you for letting us know about this issue. I will take a look and see if I can identify the root cause of why you are experiencing these hangs and will update you with the status of getting this resolved.

**Comment by abagusetty** [comment]
> Hello, thank you for letting us know about this issue. I will take a look and see if I can identify the root cause of why you are experiencing these hangs and will update you with the status of getting this resolved.

Thanks again for looking into this. Please let me know if you need more info. (compute runtime, compiler and anytests that I can try on my end)

**Comment by abagusetty** [comment]
Compiler: Intel LLVM 
PI backend: L0
Runtime: https://github.com/intel/compute-runtime/releases/tag/22.53.25242.13

Cmake & build instructions:
```bash
cmake -H. -Bbuild_sycl_aot_sg16 -DCMAKE_CXX_STANDARD=17 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PWD/build_sycl_aot_sg16 -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_FLAGS="-fsycl -fsycl-default-sub-group-size=16" -DONEDPL_ENABLE_SIMD=OFF -DONEDPL_USE_AOT_COMPILATION=ON -DONEDPL_AOT_ARCH=12.60.7 -DONEDPL_BACKEND=dpcpp_only -DONEDPL_DEVICE_TYPE=gpu -DONEDPL_DEVICE_BACKEND=level_zero -DONEDPL_USE_UNNAMED_LAMBDA=ON ./

cd build_sycl_aot_sg16

make VERBOSE=1 build-onedpl-tests -j32 -k || true
ctest --output-on-failure
```

**Comment by abagusetty** [comment]
@mmichel11 Just reaching out to see if you have any info on the above hangs. Could probably boil down to compute-runtime, but just wanted to check if any of the oneDPL kernels strongly rely on sub-group sizes of 32.

**Comment by mmichel11** [comment]
> @mmichel11 Just reaching out to see if you have any info on the above hangs. Could probably boil down to compute-runtime, but just wanted to check if any of the oneDPL kernels strongly rely on sub-group sizes of 32.

Hi @abagusetty. We have looked into this issue on PVC and have been unable to reproduce this issue when specifying the subgroup size of 16. The issue seems to most likely be caused by the compute runtime you are using. 

With regards to your question, we only explicitly fix the sub-group size within the single work group radix sort kernel to either 16 or 32 depending on the input size, so this would be the only area where this build option may cause issues.

**Comment by abagusetty** [comment]
@mmichel11 Upon updating to the latest compute runtime and the DPC++ compiler version:
DPC++: https://github.com/intel/llvm/commit/0ce9b5f9a67034ba11f5d9854c66d2bfba97d0f9
runtime: https://github.com/intel/compute-runtime/releases/tag/23.09.25812.14

The hangs are not seen, however there are several tests failing with. I will open an other issue to follow-up accordingly. Thanks!
```
terminate called after throwing an instance of 'sycl::_V1::nd_range_error'
  what():  Non-uniform work-groups are not supported by the target device -54 (PI_ERROR_INVALID_WORK_GROUP_SIZE)
```
