### ISSUE TITLE
Linking failures for log.pass, pow_complex_scalar.pass

### ISSUE THREAD

**Issue by abagusetty** [oneapi-src/oneDPL#865]
Using the latest DPCPP compiler, 've encountered this error. I am not completely sure if this is related to dpcpp compiler (intel/llvm). 

Compiler: 
```bash
clang++ -v
clang version 17.0.0 (https://github.com/intel/llvm.git 992ef064289fd5f436eaf7d448fc2b6d54a647bc)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: ..../llvm/build/bin
Found candidate GCC installation: /opt/cray/pe/gcc/11.2.0/snos/lib/gcc/x86_64-suse-linux/11.2.0
Selected GCC installation: /opt/cray/pe/gcc/11.2.0/snos/lib/gcc/x86_64-suse-linux/11.2.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
```
Error:
```bash
InvalidFunctionCall: Unexpected llvm intrinsic:
 llvm.is.fpclass.f64 [Src: ..../llvm/llvm-spirv/lib/SPIRV/SPIRVWriter.cpp:4286 false ]
llvm-foreach: 
clang++: error: llvm-spirv command failed with exit code 8 (use -v to see invocation)
```

**Comment by MrSidims** [comment]
Hi, `InstCombine` in LLVM started to generate this intrinsic quite recently. https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1922 - this patch emulates work of this intrinsic replacing it with sequence of SPIR-V instructions and should help once in lands in downstream.

**Comment by MrSidims** [comment]
> @MrSidims That makes great sense, thanks so much for the pointer. I will retest with the above spirv.

I'm not sure if the patch in intel/llvm already, it may take one more week to be pulled (unless you plan to build KHR llvm-spirv and use it for testing)

**Comment by abagusetty** [comment]
> > @MrSidims That makes great sense, thanks so much for the pointer. I will retest with the above spirv.
> 
> I'm not sure if the patch in intel/llvm already, it may take one more week to be pulled (unless you plan to build KHR llvm-spirv and use it for testing)

That is correct, I was building the KHR llvm-spirv* tools from pulling specific version of commits. Will keep a watch out.

**Comment by abagusetty** [comment]
The above errors are resolved with using:
DPC++: https://github.com/intel/llvm/commit/0ce9b5f9a67034ba11f5d9854c66d2bfba97d0f9
runtime: https://github.com/intel/compute-runtime/releases/tag/23.09.25812.14
