### ISSUE TITLE
minmax may be faster than min and max

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/oneDPL#873]
I tried to evaluate onedpl and thrust min/max functions. Please see the experimental results on an Nvidia V100 GPU.

./main 100000 1000
Total number of points: 264708400
Average execution time of thrust:min() and thrust:max(): 5681.332520 (us)
Average execution time of thrust:min_max(): 2873.853516 (us)
PASS

./main 100000 1000
Total number of points: 264708400
Average execution time of onedpl:min() and onedpl:max(): 8479.713867 (us)
Average execution time of onedpl:min_max(): 21022.216797 (us)
PASS

Reference
https://github.com/zjin-lcf/HeCBench/tree/master/minmax-cuda
https://github.com/zjin-lcf/HeCBench/tree/master/minmax-sycl

**Comment by julianmi** [comment]
Thank you for reporting this, @jinz2014. I will try to reproduce you results and get back to you.

One thing you might want to try is the current mainline oneDPL version. We have been working on multiple performance improvements to the family of reduce algorithms. `onedpl::min_element()`, `onedpl::max_element()`, and `onedpl::minmax_element()` should also benefit from the recently merged #872.

**Comment by jinz2014** [comment]
I evaluated the program again. I look forward to your evaluation. Thanks.
Average execution time of onedpl:min() and onedpl:max(): 9520.060547 (us)
Average execution time of onedpl:min_max(): 20418.228516 (us)

**Comment by jinz2014** [comment]
If the timing measurement is not accurate due to hidden data transfers from host to device using SYCL buffers, I will update the program.

**Comment by julianmi** [comment]
> I evaluated the program again. I look forward to your evaluation. Thanks. Average execution time of onedpl:min() and onedpl:max(): 9520.060547 (us) Average execution time of onedpl:min_max(): 20418.228516 (us)

Thanks for repeating the measurements. Which compiler and CUDA version did you use?

> If the timing measurement is not accurate due to hidden data transfers from host to device using SYCL buffers, I will update the program.

I expect the `d_points` buffer to reside on the device since there is no host accessor in the measurement loops. But I will verify this and get back to you.

**Comment by jinz2014** [comment]
It is CUDA 11.8. The SYCL compiler with CUDA support is clang version 16.0.0 (https://github.com/JackAKirk/llvm.git dac39b425c9e8adff50fccb6268e988ebf583a26). Thanks.

**Comment by julianmi** [comment]
I could only try your code on an A100 GPU where the issue apparently doesn't exist:

Total number of points: 264708400
Average execution time of onedpl:min() and onedpl:max(): 4620.426758 (us)
Average execution time of onedpl:min_max(): 3111.816162 (us)                                                                
PASS 

I think there is a simple performance improvement possible by removing the index checks in the comparison. I have a branch up here https://github.com/oneapi-src/oneDPL/tree/dev/julianmi/mimmax_performance and @joeatodd seems to have come to the same conclusion. I see some performance improvements on A100:

Total number of points: 264708400
Average execution time of onedpl:min() and onedpl:max(): 4626.806641 (us)
Average execution time of onedpl:min_max(): 2533.574463 (us)

PASS

Would you mind trying these changes?

**Comment by jinz2014** [comment]
Thank you for the optimization. The performance improvement is significant.
