### ISSUE TITLE
`lower_bound` and `upper_bound`

### ISSUE THREAD

**Issue by BenBrock** [oneapi-src/oneDPL#923]
`oneapi::dpl::lower_bound` and `oneapi::dpl::upper_bound` take [an extra pair of iterators](https://github.com/oneapi-src/oneDPL/blob/main/include/oneapi/dpl/internal/binary_search_extension_defs.h#L31) compared to the standard.

What's the API meant to be here?  I see both pairs are input iterators.  What is the second set of iterators meant to be?

**Comment by timmiesmith** [comment]
The semantics of the algorithm are described in the [oneDPL Spec](https://spec.oneapi.io/versions/latest/elements/oneDPL/source/parallel_api.html) and in the [oneDPL documentation](https://oneapi-src.github.io/oneDPL/parallel_api/additional_algorithms.html)

The second input iterator pair is the set of values for which the lower_bound computation should be performed. The lower_bound computations for each value are performed in parallel.

**Comment by BenBrock** [comment]
Thanks for the link.
