### ISSUE TITLE
Link in documentation is broken

### ISSUE THREAD

**Issue by reble** [oneapi-src/oneDPL#928]
Link to oneAPI specification in
https://github.com/oneapi-src/oneDPL/blob/main/documentation/library_guide/parallel_api/execution_policies.rst
is broken. 

Also looks like there is something off with the rendering: `|onedpl_long| (|onedpl_short|)`

**Comment by timmiesmith** [comment]
The broken link has been resolved. The rendering of the '_long' and '_short' names for oneDPL and oneTBB are still not displaying as expected.
