### ISSUE TITLE
Wrong work-group size computed in radix_sort

### ISSUE THREAD

**Issue by joeatodd** [oneapi-src/oneDPL#955]
I think I found a bug while looking at the current radix sort implementation.

On [this line](https://github.com/oneapi-src/oneDPL/blob/8b03924ddbaa1de82fac794a1fa18903f77231f9/include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h#LL607C20-L607C20), the computed maximum work-group size  is divided by the number of radix states:

``` c++
__block_size = oneapi::dpl::__internal::__dpl_ceiling_div(__max_count_wg_size, __radix_states);
```

On my system with an RTX 3060, this results in a `__block_size` of 2. I suspect what is intended here is to round `__max_count_wg_size` up to a multiple of __radix_states, e.g.:

``` c++
__block_size = oneapi::dpl::__internal::__dpl_ceiling_div(__max_count_wg_size, __radix_states) *  __radix_states;
```

At present, this bug is made semi-benign by the next line:

``` c++
__block_size = sycl::max(oneapi::dpl::__internal::__dpl_bit_floor(__block_size), ::std::size_t(__radix_states));
```

which produces `__block_size` of 16, assuming `__radix_states = 16`. Obviously this still isn't ideal, esp. on Nvidia hardware.

**Comment by MikeDvorskiy** [comment]
Hello, @joeatodd 
Why "this still isn't ideal, esp. on Nvidia hardware."? Do you mean subgroup size should be 32 in case of NVidia warp?

**Comment by joeatodd** [comment]
Hi @MikeDvorskiy,

Yes the fix I mentioned is what I'm using in my local branch. It works. I flagged this as an issue (rather than PR) because I wasn't totally confident it was a bug. If you agree it's a bug, I'm happy to push a PR to fix it.

> Do you mean subgroup size should be 32 in case of NVidia warp?

Yes that's right. And with the proposed fix, the block_size is indeed 32 on Nvidia hardware.

**Comment by MikeDvorskiy** [comment]
Good.  We just have discussed in our team internally and tend to conclusion that it is a bug. So, you may  push PR to fix.
Thank you!

**Comment by dmitriy-sobolev** [comment]
I guess the issue has been solve with merging #975. I am closing it.
