### ISSUE TITLE
Link in Release Notes is broken

### ISSUE THREAD

**Issue by Alexandr-Konovalov** [oneapi-src/oneDPL#967]
Please [look at](https://github.com/oneapi-src/oneDPL/blob/07de70c504282266b7d5796c808e787b70e471fb/documentation/release_notes.rst?plain=1#L33)

See oneDPL Guide for other [restrictions and known limitations](https://oneapi-src.github.io/oneDPL/overview.html#restrictions).

**Comment by ValentinaKats** [comment]
Thank you, Alexandr, for letting us know. The correct link is https://oneapi-src.github.io/oneDPL/introduction.html#restrictions. I'll update it in the Release Notes.
